
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distrubution"
  lane :firebase_distribution do
    firebase_app_distribution(
            app: "1:123456789:android:abcd1234",
            testers: "tester1@company.com, tester2@company.com",
            release_notes: "Lots of amazing new features to test out!"
        )

  end
end